# pyproject.toml

[tool.black]
line-length = 200  # Set your preferred line length
target-version = ['py311']  # Set your target Python version
include = '\\.pyi?$'
exclude = '''
    /(
        \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
'''

[tool.mypy]
ignore_missing_imports = true  # Ignore errors for missing imports
strict_optional = true  # Enable strict checking of optional types
warn_unused_configs = true  # Warn about unused configuration options in mypy.ini files
disallow_incomplete_defs = false  # Disallow incomplete function definitions
check_untyped_defs = true  # Type-check the interior of functions without type annotations
disallow_untyped_defs = false  # Type-check the interior of functions without type annotations
disallow_subclassing_any = false  # Disallow subclassing from classes defined with type Any
no_implicit_optional = false  # Change the default behavior of None and optional types
warn_redundant_casts = true  # Warn about redundant casts
warn_unused_ignores = true  # Warn about unneeded '# type: ignore' comments
warn_return_any = false  # Warn about returning values with type 'Any' from functions declared with a non-'Any' type
show_error_codes = false  # Show error codes in error messages